// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"khalif-comment/internal/config"
	"khalif-comment/internal/handler"
	"khalif-comment/internal/repository"
	"khalif-comment/internal/usecase"
)

import (
	_ "khalif-comment/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig := config.LoadConfig()
	db := ProvideDB(configConfig)
	client := ProvideRedis(configConfig)
	commentRepo := repository.NewCommentRepository(db)
	redisRepo := repository.NewCacheRepository(client)
	commentUC := usecase.NewCommentUseCase(commentRepo, redisRepo)
	commentHandler := handler.NewCommentHandler(commentUC)
	app := NewApp(db, client, commentHandler)
	return app, nil
}
